### ISSUE TITLE
Accepting PRs?

### ISSUE THREAD

**Issue by lipchev** [ezhassen/Live-Charts#1]
Hi,
Seeing that this is the only other nuget out there- I was wondering if you'd be willing to accept pull requests? 
Honestly, I can no longer stand the [MouseCapture issue](https://github.com/Live-Charts/Live-Charts/pull/979).. Also If I could just get rid of a few of those `internal override` that would help a lot! So if you are willing branch away from 0.97 I'd love to make a few PRs.

**Comment by ezhassen** [comment]
Sorry I'm not active these days but any contribution are welcomed 😊 (clone branch [netcoreapp3.1Master](https://github.com/ezhassen/Live-Charts/tree/netcoreapp3.1Master))

**Comment by KeithBrio** [comment]
Did anyone fork off this in the end?
